version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - gosec
    - prealloc
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US
    gosec:
      excludes:
        - G104
        - G304

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/randomtoy/random-chess-backend

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
